// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package qxTypes

type ApiCaptchaGenerateReq struct {
	Key       string  `json:"key,optional"`
	DotCount  int32   `json:"dot_count,optional"`
	MaxSkew   float64 `json:"max_skew,optional"`
	KeyLong   int32   `json:"key_long,optional"`
	ImgWidth  int32   `json:"img_width,optional"`
	ImgHeight int32   `json:"img_height,optional"`
}

type ApiCaptchaGenerateResp struct {
	Key     string `json:"key,omitempty"`
	Id      string `json:"id,omitempty"`
	Content string `json:"content,omitempty"`
	Answer  string `json:"answer,omitempty"`
	Img     string `json:"img,omitempty"`
}

type ApiCaptchaGenerateRespData struct {
	Key     string `json:"key,omitempty"`
	Id      string `json:"id,omitempty"`
	Content string `json:"content,omitempty"`
	Answer  string `json:"answer,omitempty"`
	Img     string `json:"img,omitempty"`
}

type ApiSmsSendReq struct {
	Key    string   `json:"key"`
	Mobile string   `json:"mobile"`
	Params []string `json:"params,optional"`
}

type ApiSmsSendResp struct {
	RequestID string `json:"requestId"`
}

type BehavioralVerificationInitReq struct {
	Key     string `json:"key"`
	Service string `json:"service"`
	Type    string `json:"type"`
}

type BehavioralVerificationInitResp struct {
	Id      string `json:"id,omitempty"`
	Content string `json:"content,omitempty"`
	Answer  string `json:"answer,omitempty"`
	Img     string `json:"img,omitempty"`
}

type BehavioralVerificationVerifyReq struct {
	Id         string `json:"id"`
	Service    string `json:"service"`
	Type       string `json:"type"`
	VerifyCode string `json:"verify_code"`
}

type BehavioralVerificationVerifyResp struct {
	Result bool `json:"result"`
}

type BootstrapReq struct {
	AccessKey    string `form:"access_key"`
	AccessSecret string `form:"access_secret"`
}

type BootstrapResp struct {
}

type CodesReq struct {
	Lang string `form:"lang,optional" url:"lang"`
	Svc  string `form:"svc,optional" url:"svc"`
}

type CodesResp struct {
	List     []ModelCode `json:"list"`
	Total    int64       `json:"total"`
	Page     int32       `json:"page"`
	PageSize int32       `json:"page_size"`
}

type CreateBucketAndConfigReq struct {
	ConfigKey    string `json:"config_key"`
	StorageType  string `json:"storage_type"`
	AppId        string `json:"app_id,optional"`
	AccessKey    string `json:"access_key"`
	AccessSecret string `json:"access_secret"`
	BucketKey    string `json:"bucket_key"`
	Name         string `json:"name"`
	Region       string `json:"region"`
	IsAccelerate int32  `json:"is_accelerate"`
	Prefix       string `json:"prefix"`
	StaticDomain string `json:"static_domain"`
	CdnDomain    string `json:"cdn_domain"`
}

type CreateBucketAndConfigResp struct {
}

type CreateBucketNoConfigReq struct {
	ConfigKey    string `json:"config_key"`
	BucketKey    string `json:"bucket_key"`
	Name         string `json:"name"`
	Region       string `json:"region"`
	IsAccelerate int32  `json:"is_accelerate"`
	Prefix       string `json:"prefix"`
	StaticDomain string `json:"static_domain"`
	CdnDomain    string `json:"cdn_domain"`
}

type CreateBucketNoConfigResp struct {
}

type EncryptReq struct {
	Data string `json:"data"`
}

type EncryptResp struct {
	Data string `json:"data"`
}

type HealthzResp struct {
}

type IpWhiteReq struct {
	AccessKey string `json:"access_key"`
	Ip        string `json:"ip"`
	Remark    string `json:"remark"`
}

type IpWhiteResp struct {
}

type KmsAkcCreateKeychainReq struct {
	CertType string `json:"cert_type"`
	Name     string `json:"name"`
}

type KmsAkcCreateKeychainResp struct {
	Status     string `json:"status"`
	Name       string `json:"name"`
	SignMethod string `json:"sign_method"`
	CertType   string `json:"cert_type"`
	PublicKey  string `json:"public_key"`
}

type KmsAkcGetKeychainPublicKeyReq struct {
	Name string `json:"name"`
}

type KmsAkcGetKeychainPublicKeyResp struct {
	Name       string `json:"name"`
	SignMethod string `json:"sign_method"`
	CertType   string `json:"cert_type"`
	PublicKey  string `json:"public_key"`
}

type KmsAkcSignReq struct {
	Name        string `json:"name"`
	SignContent string `json:"sign_content"`
}

type KmsAkcSignResp struct {
	Name string `json:"name"`
	Sign string `json:"sign"`
}

type KmsAkcVerifyReq struct {
	Name        string `json:"name"`
	SignContent string `json:"sign_content"`
	Sign        string `json:"sign"`
}

type KmsAkcVerifyResp struct {
	Name   string `json:"name"`
	Verify bool   `json:"verify"`
}

type KmsSkcBatchDecryptReq struct {
	Data map[string]KmsSkcBatchDecryptReqItem `json:"data"`
}

type KmsSkcBatchDecryptReqItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcBatchDecryptResp struct {
	Data map[string]KmsSkcBatchDecryptRespItem `json:"data"`
}

type KmsSkcBatchDecryptRespItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcBatchEncryptReq struct {
	Data map[string]KmsSkcBatchEncryptReqItem `json:"data"`
}

type KmsSkcBatchEncryptReqItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcBatchEncryptResp struct {
	Data map[string]KmsSkcBatchEncryptRespItem `json:"data"`
}

type KmsSkcBatchEncryptRespItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcCompareItem struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcCompareReq struct {
	List []KmsSkcCompareItem `json:"list"`
}

type KmsSkcCompareResp struct {
	Status      string                      `json:"status"`
	CompareData bool                        `json:"compare_data"`
	List        []KmsSkcCompareRespDataItem `json:"list"`
}

type KmsSkcCompareRespData struct {
	Status      string                      `json:"status"`
	CompareData bool                        `json:"compare_data"`
	List        []KmsSkcCompareRespDataItem `json:"list"`
}

type KmsSkcCompareRespDataItem struct {
	Status   string `json:"status"`
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcCreateKeychainReq struct {
	Algorithm string `json:"algorithm"`
	Name      string `json:"name"`
}

type KmsSkcCreateKeychainResp struct {
	Status string `json:"status"`
	Name   string `json:"name"`
}

type KmsSkcDecryptReq struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcDecryptResp struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcEncryptReq struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type KmsSkcEncryptResp struct {
	Name     string `json:"name"`
	BaseData string `json:"base_data"`
}

type ModelCode struct {
	Code string `json:"code"`
	Num  int32  `json:"num"`
	Msg  string `json:"msg"`
}

type ModelZone struct {
	Label string `json:"label"`
	Code  string `json:"code"`
	Area  string `json:"area"`
}

type SasPresignerHeadObjectReq struct {
	BucketKey string `json:"bucket_key"`
	Path      string `json:"path"`
}

type SasPresignerHeadObjectResp struct {
	Url    string `json:"url"`
	Method string `json:"method"`
}

type SasPresignerUploadReq struct {
	BucketKey string `json:"bucket_key"`
	Path      string `json:"path"`
}

type SasPresignerUploadResp struct {
	Url    string            `json:"url"`
	Fields map[string]string `json:"fields"`
}

type SasQueryBucketReq struct {
	BucketKey string `json:"bucket_key"`
}

type SasQueryBucketResp struct {
	Name                   string `json:"name"`
	Prefix                 string `json:"prefix"`
	Region                 string `json:"region"`
	BucketInternetDomain   string `json:"bucket_internet_domain"`
	BucketInternalDomain   string `json:"bucket_internal_domain"`
	IsAccelerate           int32  `json:"is_accelerate"`
	BucketAccelerateDomain string `json:"bucket_accelerate_domain"`
	StaticDomain           string `json:"static_domain"`
	CdnDomain              string `json:"cdn_domain"`
}

type SmsInitReq struct {
	Key     string `json:"key"`
	Service string `json:"service"`
	Type    string `json:"type"`
	Zone    string `json:"zone"`
	Phone   string `json:"phone"`
}

type SmsInitResp struct {
	Status string `json:"status"`
}

type SmsVerifyReq struct {
	Service    string `json:"service"`
	Type       string `json:"type"`
	Zone       string `json:"zone"`
	Phone      string `json:"phone"`
	VerifyCode string `json:"verify_code"`
}

type SmsVerifyResp struct {
	Result bool `json:"result"`
}

type ZonesReq struct {
	Lang string `form:"lang,optional" url:"lang"`
}

type ZonesResp struct {
	List     []ModelZone `json:"list"`
	Total    int64       `json:"total"`
	Page     int32       `json:"page"`
	PageSize int32       `json:"page_size"`
}
